from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        #-----设置主窗口------
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        #-----设置菜单栏--------
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        #-----在菜单栏添加File、Edit、View和Help-----
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setFont(font)
        self.menuEdit.setObjectName("menuFile")
        
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setFont(font)
        self.menuView.setObjectName("menuFile")
        
        self.menuSAM = QtWidgets.QMenu(self.menubar)
        self.menuSAM.setFont(font)
        self.menuSAM.setObjectName("menuSAM")
        
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setFont(font)
        self.menuHelp.setObjectName("menuFile")
        #-----添加功能按钮------
        self.actionOpen_image_dir = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/照片_pic.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_image_dir.setIcon(icon1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.actionOpen_image_dir.setFont(font)
        self.actionOpen_image_dir.setObjectName("actionOpen_image_dir")
        
        self.actionOpen_save_dir = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/文件夹-开_folder-open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_save_dir.setIcon(icon2)
        self.actionOpen_save_dir.setWhatsThis("")
        self.actionOpen_save_dir.setFont(font)
        self.actionOpen_save_dir.setObjectName("actionOpen_mask_dir")
        
        self.actionPrevious_image = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/上一步_back.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrevious_image.setIcon(icon3)
        self.actionPrevious_image.setFont(font)
        self.actionPrevious_image.setObjectName("actionPrevious_image")
        
        self.actionNext_image = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/下一步_next.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext_image.setIcon(icon4)
        self.actionNext_image.setFont(font)
        self.actionNext_image.setObjectName("actionNext_image")
        
        self.actionSetting = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/设置_setting-two.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSetting.setIcon(icon5)
        self.actionSetting.setFont(font)
        self.actionSetting.setObjectName("setting")
        
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/开关_power.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon6)
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("Exit")
        
        self.actionDelete = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/删除_delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon7)
        self.actionDelete.setFont(font)
        self.actionDelete.setObjectName("Delete")
        
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/保存_save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon8)
        self.actionSave.setFont(font)
        self.actionSave.setObjectName("Save")
        
        self.actionFitWindow = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/全宽_fullwidth.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFitWindow.setIcon(icon9)
        self.actionFitWindow.setFont(font)
        self.actionFitWindow.setObjectName("Fit Window")
        
        self.actionShortCut = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/键盘_keyboard-one.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShortCut.setIcon(icon10)
        self.actionShortCut.setFont(font)
        self.actionShortCut.setObjectName("ShortCut")
        
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/我的_me.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon11)
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName("About")
        
        self.actionVisible = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/眼睛_eyes.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVisible.setIcon(icon12)
        self.actionVisible.setFont(font)
        self.actionVisible.setObjectName("Visible")
        
        self.actionPolygon = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons/锚点_anchor.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPolygon.setIcon(icon13)
        self.actionPolygon.setFont(font)
        self.actionPolygon.setObjectName("Polygon")
        
        self.actionCancel = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icons/关闭_close-one.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCancel.setIcon(icon14)
        self.actionCancel.setFont(font)
        self.actionCancel.setObjectName("Polygon")
        
        self.actionFinish = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icons/校验_check-one.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFinish.setIcon(icon15)
        self.actionFinish.setFont(font)
        self.actionFinish.setObjectName("actionFinish")
        
        self.actionObjectRemoval = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("icons/编辑撰写_writing-fluently.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionObjectRemoval.setIcon(icon16)
        self.actionObjectRemoval.setFont(font)
        self.actionObjectRemoval.setObjectName("actionObjectRemoval")
        
        self.actionChangeView = QtWidgets.QAction(MainWindow)
        self.actionChangeView.setIcon(icon1)
        self.actionChangeView.setFont(font)
        self.actionChangeView.setObjectName("changeView")
        
        self.actionSegment_anything_point = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("icons/M_Favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSegment_anything_point.setIcon(icon17)
        self.actionSegment_anything_point.setFont(font)
        self.actionSegment_anything_point.setObjectName("actionSegment_anything_point")
        
        #-----设置窗口--------
        self.results = QtWidgets.QDockWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.results.setFont(font)
        self.results.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.results.setAcceptDrops(False)
        self.results.setObjectName("Labels")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.resultsWidget = QtWidgets.QWidget(self.dockWidgetContents_2)
        self.resultsWidget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.resultsWidget)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_visible = QtWidgets.QCheckBox(self.resultsWidget)
        self.checkBox_visible.setStatusTip("")
        self.checkBox_visible.setObjectName("checkBox_visible")
        self.reverse_mask = QtWidgets.QCheckBox(self.resultsWidget)
        self.reverse_mask.setObjectName("reverse mask")
        self.horizontalLayout_2.addWidget(self.checkBox_visible)
        self.horizontalLayout_2.addWidget(self.reverse_mask)
        self.verticalLayout_2.addWidget(self.resultsWidget)
        self.listWidget_results = QtWidgets.QListWidget(self.dockWidgetContents_2)
        self.listWidget_results.setObjectName("listWidget_Masks")
        self.verticalLayout_2.addWidget(self.listWidget_results)
        self.pushButton_add_manually = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.pushButton_add_manually.setObjectName("pushButton_add_manually")
        self.verticalLayout_2.addWidget(self.pushButton_add_manually)
        self.results.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.results)
        
        self.Files = QtWidgets.QDockWidget(MainWindow)
        self.Files.setObjectName("Files")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidgetFiles = QtWidgets.QListWidget(self.dockWidgetContents)
        self.listWidgetFiles.setObjectName("listWidgetFiles")
        self.verticalLayout.addWidget(self.listWidgetFiles)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_jump = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit_jump.setFont(font)
        self.lineEdit_jump.setObjectName("lineEdit_jump")
        self.horizontalLayout.addWidget(self.lineEdit_jump)
        self.label_files = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_files.setMinimumSize(QtCore.QSize(50, 0))
        self.label_files.setText("")
        self.label_files.setTextFormat(QtCore.Qt.AutoText)
        self.label_files.setScaledContents(False)
        self.label_files.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_files.setObjectName("label_files")
        self.horizontalLayout.addWidget(self.label_files)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.Files.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.Files)
        
        self.status_bar = QtWidgets.QStatusBar(MainWindow)
        self.status_bar.setObjectName("status_bar")
        MainWindow.setStatusBar(self.status_bar)
        
        # self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        # self.dockWidget.setObjectName("dockWidget")
        # self.dockWidgetContents_3 = QtWidgets.QWidget()
        # self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        # self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        # self.verticalLayout_3.setObjectName("verticalLayout_3")
        # self.listWidget_categories = QtWidgets.QListWidget(self.dockWidgetContents_3)
        # self.listWidget_categories.setObjectName("listWidget_categories")
        # self.verticalLayout_3.addWidget(self.listWidget_categories)
        # self.dockWidget.setWidget(self.dockWidgetContents_3)
        # MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        
        #-----设置工具栏-----
        self.ToolBar = QtWidgets.QToolBar(MainWindow)
        self.ToolBar.setOrientation(QtCore.Qt.Horizontal)
        self.ToolBar.setIconSize(QtCore.QSize(24, 24))
        self.ToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.ToolBar.setObjectName("toolbar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.ToolBar)
        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        #-----将功能加入UI中------
        self.menuFile.addAction(self.actionOpen_image_dir)
        self.menuFile.addAction(self.actionOpen_save_dir)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrevious_image)
        self.menuFile.addAction(self.actionNext_image)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSetting)
        self.menuFile.addAction(self.actionExit)
        
        self.menuEdit.addAction(self.actionSegment_anything_point)
        self.menuEdit.addAction(self.actionPolygon)
        self.menuEdit.addAction(self.actionObjectRemoval)
        self.menuEdit.addAction(self.actionFinish)
        self.menuEdit.addAction(self.actionCancel)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionSave)
        
        self.menuView.addAction(self.actionFitWindow)
        self.menuView.addAction(self.actionVisible)
        self.menuView.addAction(self.actionChangeView)
        
        self.menuHelp.addAction(self.actionShortCut)
        self.menuHelp.addAction(self.actionAbout)
        
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSAM.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        
        self.ToolBar.addAction(self.actionOpen_image_dir)
        self.ToolBar.addAction(self.actionOpen_save_dir)
        self.ToolBar.addSeparator()
        self.ToolBar.addAction(self.actionPrevious_image)
        self.ToolBar.addAction(self.actionNext_image)
        self.ToolBar.addSeparator()
        self.ToolBar.addAction(self.actionSegment_anything_point)
        self.ToolBar.addAction(self.actionPolygon)
        self.ToolBar.addAction(self.actionObjectRemoval)
        self.ToolBar.addAction(self.actionFinish)
        self.ToolBar.addAction(self.actionCancel)
        self.ToolBar.addSeparator()
        self.ToolBar.addAction(self.actionDelete)
        self.ToolBar.addAction(self.actionSave)
        self.ToolBar.addSeparator()
        self.ToolBar.addAction(self.actionFitWindow)
        self.ToolBar.addAction(self.actionVisible)
        self.ToolBar.addAction(self.actionChangeView)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuSAM.setTitle(_translate("MainWindow", "SAM"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        
        self.actionOpen_image_dir.setText(_translate("MainWindow", "Image Dir"))
        self.actionOpen_image_dir.setStatusTip(_translate("MainWindow", "Open Image Directory."))
        self.actionOpen_save_dir.setText(_translate("MainWindow", "results dir"))
        self.actionOpen_save_dir.setStatusTip(_translate("MainWindow", "Open Results Directory."))
        self.actionPrevious_image.setText(_translate("MainWindow", "Previous Omage"))
        self.actionNext_image.setText(_translate("MainWindow", "Next Image"))
        self.actionSetting.setText(_translate("MainWindow", "Setting"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        
        self.actionSegment_anything_point.setText(_translate("MainWindow", "SegmentAny"))
        self.actionSegment_anything_point.setToolTip(_translate("MainWindow", "Segment Anything Point"))
        self.actionPolygon.setText(_translate("MainWindow", "Polygon"))
        self.actionPolygon.setToolTip(_translate("MainWindow", "Draw polygon"))
        self.actionObjectRemoval.setText(_translate("MainWindow", "Object Removal"))
        self.actionObjectRemoval.setToolTip(_translate("MainWindow", "Object Removal or Inpainting"))
        self.actionFinish.setText(_translate("MainWindow", "Finish draw mask"))
        self.actionCancel.setText(_translate("MainWindow", "Cancel draw mask"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        
        self.actionFitWindow.setText(_translate("MainWindow", "Fit Window"))
        self.actionVisible.setText(_translate("MainWindow", "Visible"))
        self.actionChangeView.setText(_translate("MainWindow", "Change View"))
        
        self.actionShortCut.setText(_translate("MainWindow", "Short Cut"))
        self.actionAbout.setText(_translate("MainWindow", "About")) 
        
        # self.dockWidget.setWindowTitle(_translate("MainWindow", "Categories Dock"))
        
        self.checkBox_visible.setText(_translate("MainWindow", "visible"))
        self.reverse_mask.setText(_translate("MainWindow", "Reverse"))
        self.pushButton_add_manually.setStatusTip(_translate("MainWindow", "Add annotation manually."))
        self.pushButton_add_manually.setText(_translate("MainWindow", "Add Manually"))
        self.results.setWindowTitle(_translate("MainWindow", "Results Dock"))

        self.Files.setWindowTitle(_translate("MainWindow", "Files Dock"))
        self.lineEdit_jump.setStatusTip(_translate("MainWindow", "Jump to the image. Input name or index."))
        self.lineEdit_jump.setPlaceholderText(_translate("MainWindow", "Jump to the image."))
        
